// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzJLdzalc9v9ah7cF9kv9LlbfFxG2URMI',
    appId: '1:202444688325:web:69f5f1773f0dd8d33e59ac',
    messagingSenderId: '202444688325',
    projectId: 'rijad-budget-app',
    authDomain: 'rijad-budget-app.firebaseapp.com',
    storageBucket: 'rijad-budget-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwefc7HlHA6yLM-CyBfc8RC1R9qvDq5i0',
    appId: '1:202444688325:android:d68c9877df3e2ec33e59ac',
    messagingSenderId: '202444688325',
    projectId: 'rijad-budget-app',
    storageBucket: 'rijad-budget-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCWVnB_d4fcUqbyeEhwrWVJ7aTNt8ByaLw',
    appId: '1:202444688325:ios:44857846fc94a3d93e59ac',
    messagingSenderId: '202444688325',
    projectId: 'rijad-budget-app',
    storageBucket: 'rijad-budget-app.firebasestorage.app',
    iosBundleId: 'com.codingliquids.budgetAppStarting',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzJLdzalc9v9ah7cF9kv9LlbfFxG2URMI',
    appId: '1:202444688325:web:05dbe23485a96d653e59ac',
    messagingSenderId: '202444688325',
    projectId: 'rijad-budget-app',
    authDomain: 'rijad-budget-app.firebaseapp.com',
    storageBucket: 'rijad-budget-app.firebasestorage.app',
  );

}